name: EKS cluster creation on development environment

on:
  workflow_dispatch:   
  push:
    branches:
        - 'development'

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1   

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0  # or whichever version you need

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: EKS/Dev/module_eks

      # Step 5: Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: EKS/Dev/module_eks

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: EKS/Dev/module_eks
      
      # Step 7: Check if EKS cluster already exists
      - name: Check EKS cluster
        id: check-cluster
        continue-on-error: true
        run: |
          aws eks describe-cluster --name first-cluster --region ca-central-1
          
      # Step 8: Terraform apply (only if cluster does not exist)
      - name: Terraform Apply
        if: steps.check-cluster.outcome == 'failure'
        run: terraform apply --auto-approve
        working-directory: EKS/Dev/module_eks

      # Step 9: Update kubeconfig file      
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region ca-central-1 \
          --name first-cluster

post-deploy:
    runs-on: ubuntu-latest
    needs: create-cluster   # ensures this runs only after cluster creation succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region ca-central-1 \
          --name first-cluster

      - name: Deploy role and role binding 
        run: |
          # Check ClusterRole
          if ! kubectl get clusterrole viewer >/dev/null 2>&1; then
            echo "ClusterRole 'viewer' not found. Creating..."
            kubectl apply -f viewer-cluster-role.yaml
          else
            echo "ClusterRole 'viewer' already exists. Skipping..."
          fi

          # Check ClusterRoleBinding
          if ! kubectl get clusterrolebinding my-viewer-binding >/dev/null 2>&1; then
            echo "ClusterRoleBinding 'my-viewer-binding' not found. Creating..."
            kubectl apply -f viewer-cluster-role-binding.yaml
          else
           echo "ClusterRoleBinding 'my-viewer-binding' already exists. Skipping..."
          fi
        working-directory: EKS/Dev/yaml_files

      - name: Install Helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm -y
          
      # Install Prometheus with LoadBalancer
      - name: Install Prometheus
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts \
          helm install my-prometheus prometheus-community/prometheus --version 27.32.0 \
          --namespace monitoring --create-namespace \
          --set server.service.type=LoadBalancer

      # Install Grafana with LoadBalancer
      - name: Install Grafana
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts \
          helm install my-grafana grafana/grafana --version 9.3.4 \
          --namespace monitoring --create-namespace \
          --set service.type=LoadBalancer \
          --set adminPassword='YourSecurePassword'