name: EKS cluster creation on development environment

on:
  workflow_dispatch:   
  push:
    branches:
        - 'development'

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1   

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0  # or whichever version you need

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: EKS/Dev/module_eks

      # Step 5: Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: EKS/Dev/module_eks

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: EKS/Dev/module_eks

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        id: apply
        run: |
          terraform apply --auto-approve=true 
      
      # Step 7: Update kubeconfig file      
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region ca-central-1 \
          --name first-cluster

      - name: Depploy role and role binding 
        run : |
          kubectl apply -f viewer-cluster-role.yaml
          kubectl apply -f viewer-cluster-role-binding.yaml
        working-directory: EKS/Dev/yaml_files
       